# Run from the extracted Blue_Jays_Database folder. Base R only.
stopifnot(dir.exists("data"))
tables <- list()
tables[["games"]] <- read.csv("data/games.csv", fileEncoding="UTF-8", na.strings="", stringsAsFactors=FALSE, check.names=FALSE, colClasses=c("character","numeric","character","character","numeric","numeric","character","character","numeric","numeric","numeric","numeric","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","character"))
stopifnot(nrow(tables[["games"]]) == 39)
tables[["batters"]] <- read.csv("data/batters.csv", fileEncoding="UTF-8", na.strings="", stringsAsFactors=FALSE, check.names=FALSE, colClasses=c("character","character"))
stopifnot(nrow(tables[["batters"]]) == 17)
tables[["plate_appearances"]] <- read.csv("data/plate_appearances.csv", fileEncoding="UTF-8", na.strings="", stringsAsFactors=FALSE, check.names=FALSE, colClasses=c("character","character","character","numeric","numeric","numeric","numeric","character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
stopifnot(nrow(tables[["plate_appearances"]]) == 1461)
tables[["pitches"]] <- read.csv("data/pitches.csv", fileEncoding="UTF-8", na.strings="", stringsAsFactors=FALSE, check.names=FALSE, colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","character","numeric","numeric","character","character","character","numeric","numeric","numeric"))
stopifnot(nrow(tables[["pitches"]]) == 5634)
tables[["project1_pitches"]] <- read.csv("data/project1_pitches.csv", fileEncoding="UTF-8", na.strings="", stringsAsFactors=FALSE, check.names=FALSE, colClasses=c("character","character","character","character","character","character","character","numeric","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","character","numeric","numeric","numeric"))
stopifnot(nrow(tables[["project1_pitches"]]) == 5631)
tables[["project2_pas"]] <- read.csv("data/project2_pas.csv", fileEncoding="UTF-8", na.strings="", stringsAsFactors=FALSE, check.names=FALSE, colClasses=c("character","character","character","character","character","character","numeric","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric","character","numeric"))
stopifnot(nrow(tables[["project2_pas"]]) == 1459)
tables[["project3_snapshots"]] <- read.csv("data/project3_snapshots.csv", fileEncoding="UTF-8", na.strings="", stringsAsFactors=FALSE, check.names=FALSE, colClasses=c("character","character","character","character","character","numeric","numeric","numeric","numeric","numeric","character","numeric"))
stopifnot(nrow(tables[["project3_snapshots"]]) == 5617)
tables[["project4_games"]] <- read.csv("data/project4_games.csv", fileEncoding="UTF-8", na.strings="", stringsAsFactors=FALSE, check.names=FALSE, colClasses=c("character","numeric","character","character","numeric","numeric","character","character","numeric","numeric","numeric","numeric","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","character"))
stopifnot(nrow(tables[["project4_games"]]) == 39)
stopifnot(!anyDuplicated(tables$pitches$pitch_id))
stopifnot(!anyDuplicated(tables$plate_appearances$pa_id))
stopifnot(all(tables$pitches$pa_id %in% tables$plate_appearances$pa_id))
stopifnot(sum(is.na(tables$pitches$routine_time_secs)) == 3)
p1_routine <- subset(tables$project1_pitches, routine_model_eligible == 1)
p1_tics <- subset(tables$project1_pitches, tics_model_eligible == 1)
p2 <- tables$project2_pas
p3 <- subset(tables$project3_snapshots, pitch_number_pa == 1)
train <- subset(p3, split == "Train")
validation <- subset(p3, split == "Validation")
test <- subset(p3, split == "Test")
predictor_names <- c("routine_time_secs", "total_tics", "pre_balls", "pre_strikes", "pitch_number_pa")
# Use target_pa_group for multiclass learning OR target_strikeout for binary learning.
# Never include the alternative target, IDs, split or game_date as predictors.
# First-pitch count and pitch number are constant. Dynamic snapshots have variable counts.
print(vapply(tables, nrow, integer(1)))
print(table(p3$split))
print(table(tables$pitches$routine_source, useNA="ifany"))
